name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' # Set this to the version of .NET Core you are using

      - name: Install dependencies
        working-directory: PyNET.Tests
        run: dotnet restore

      - name: Build
        working-directory: PyNET.Tests
        run: dotnet build --no-restore

      - name: Run tests
        working-directory: PyNET.Tests
        run: dotnet test --no-build --verbosity normal
